service: collector-api

provider:
  name: aws
  runtime: dotnetcore2.0
  stage: dev
  region: us-east-1

package:
  artifact: bin/release/netcoreapp2.0/publish/Oversight-Collector-Api.zip

functions:
  get:
    handler: Oversight.Collector.Api::Oversight.Collector.Api::Get
    events:
      - http:
          path: v1/get
          method: GET
          private: false
  save:
    handler: Oversight.Collector.Api::Oversight.Collector.Api::Save
    events:
      - http: 
          path: v1/save
          method: POST
          private: false